version: '3.8'

services:
  api_gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./api-gateway:/app/
    env_file:
     - .env
    command: npm run start:dev
    environment:
      - PORT=3000
  auth_service:
    build: ./auth
    volumes:
      - ./auth:/app/
    env_file:
     - .env
    command: npm run start:dev
  chat_service:
    build: ./chat
    volumes:
      - ./chat:/app/
    env_file:
     - .env
    command: npm run start:dev
  user_service:
    build: ./user
    volumes:
      - ./user:/app/
    env_file:
     - .env
    command: npm run start:dev
  socket_service:
    build: ./socket
    volumes:
      - ./socket:/app/
    env_file:
     - .env
    command: npm run start:dev
  nats:
    image: nats
    ports:
      - "4222:4222"
