version: '3.8'

services:
  api_gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./api-gateway:/app/
    command: npm run start:dev
    environment:
      - PORT=3000
  auth_service:
    build: ./auth
    volumes:
      - ./auth:/app/
    command: npm run start:dev
  chat_service:
    build: ./chat
    volumes:
      - ./chat:/app/
    command: npm run start:dev
  user_service:
    build: ./user
    volumes:
      - ./user:/app/
    command: npm run start:dev
  images_service:
    build: ./images
    volumes:
      - ./images:/app/
    command: npm run start:dev
  redis_service:
    build: ./redis
    volumes:
      - ./redis:/app/
    command: npm run start:dev
  nats:
    image: nats
    ports:
      - "4222:4222"
  redis:
    image: redis
    container_name: nest-redis
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
    command: ["redis-server", "/etc/redis/redis.conf"]
  
